        <!-- BLOGS & PERSONAL HUB SECTION -->
        <section id="blog">
            <div class="container section-container">
                <div class="blogs-header">
                    <div class="section-header" style="margin-bottom: 0;">
                        <span class="section-tag">/hub/knowledge-base</span>
                        <h2 class="section-title">Blogs, Travel & Gaming logs</h2>
                    </div>
                    <div style="display: flex; gap: 1rem; align-items: center; flex-wrap: wrap;">
                        <div class="blog-search-bar">
                            <i data-lucide="search" class="cmd-palette-search-icon"></i>
                            <input type="text" id="blog-search" class="blog-search-input" placeholder="Search articles...">
                        </div>
                        <div class="blog-tabs-nav" id="blog-category-tabs">
                            <button class="blog-tab-btn active" data-category="all">All Content</button>
                            <button class="blog-tab-btn" data-category="engineering">Engineering</button>
                            <button class="blog-tab-btn" data-category="travel">Travel</button>
                            <button class="blog-tab-btn" data-category="gaming">Gaming</button>
                        </div>
                    </div>
                </div>

                <div class="blog-list" id="blog-grid-list">
                    <!-- Blog cards generated by JS -->
                </div>
            </div>
        </section>